FROM althack/ros2:humble-full
# FROM tiryoh/ros2:humble

# source /opt/ros/humble/setup.bash for docker containers
RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc

CMD ["ros2", "run", "joy", "game_controller_node"]
